name: Ada (GNAT)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@master
  
    - name: Set up GNAT toolchain
      run: >
        sudo apt-get update &&
        sudo apt-get install gnat gprbuild make qt5-default qt5-qmake qtbase5-dev-tools qt3d5-dev "qt5-*plugins" "qt3d-*-plugin" "libqt5*5" "libqt5*5-plugins" libspeechd2 libpulse-dev

    - name: Build
      run: make

    - name: Build AppImage
      run: make AppImage


    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: True
        tag: continuous
        name: Continuous build
        prerelease: True
        artifacts: "COVID*.AppImage"
        token: ${{ secrets.GITHUB_TOKEN }}
